definitions:
  environment:
    ios_release_environment: &ios_release_environment
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: ly.zakatfund.radioapp

workflows:
  ios-ipa:
    name: iOS IPA
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      <<: *ios_release_environment
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Analyze Flutter project
        script: flutter analyze
      - name: Run Flutter tests
        script: flutter test
      - name: Set up iOS code signing
        script: xcode-project use-profiles
      - name: Build signed iOS IPA
        script: flutter build ipa --release --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

  ios-testflight:
    name: iOS TestFlight Upload
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      <<: *ios_release_environment
      groups:
        - appstore_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Analyze Flutter project
        script: flutter analyze
      - name: Run Flutter tests
        script: flutter test
      - name: Set up iOS code signing
        script: xcode-project use-profiles
      - name: Build signed iOS IPA
        script: flutter build ipa --release --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
